services:
    api_histogram.dynamic_repository:
        class: ApiHistogram\ApiHistogramBundle\Repository\Dynamic\DynamicRepository
        arguments:
            - @doctrine
            - @api_histogram.site_manager